
Traceback (most recent call last):
  File "tests/exceptions/source/others/sys_tracebacklimit.py", line 33, in f
    g()
  File "tests/exceptions/source/others/sys_tracebacklimit.py", line 37, in g
    h()
  File "tests/exceptions/source/others/sys_tracebacklimit.py", line 41, in h
    i()
  File "tests/exceptions/source/others/sys_tracebacklimit.py", line 45, in i
    j(1, 0)
  File "tests/exceptions/source/others/sys_tracebacklimit.py", line 49, in j
    a / b
ZeroDivisionError: division by zero

Traceback (most recent call last):

  File "tests/exceptions/source/others/sys_tracebacklimit.py", line 33, in f
    g()
    └ <function g at 0xDEADBEEF>

  File "tests/exceptions/source/others/sys_tracebacklimit.py", line 37, in g
    h()
    └ <function h at 0xDEADBEEF>

  File "tests/exceptions/source/others/sys_tracebacklimit.py", line 41, in h
    i()
    └ <function i at 0xDEADBEEF>

  File "tests/exceptions/source/others/sys_tracebacklimit.py", line 45, in i
    j(1, 0)
    └ <function j at 0xDEADBEEF>

  File "tests/exceptions/source/others/sys_tracebacklimit.py", line 49, in j
    a / b
    │   └ 0
    └ 1

ZeroDivisionError: division by zero

Traceback (most recent call last):
  File "tests/exceptions/source/others/sys_tracebacklimit.py", line 33, in f
    g()
  File "tests/exceptions/source/others/sys_tracebacklimit.py", line 37, in g
    h()
  File "tests/exceptions/source/others/sys_tracebacklimit.py", line 41, in h
    i()
  File "tests/exceptions/source/others/sys_tracebacklimit.py", line 45, in i
    j(1, 0)
  File "tests/exceptions/source/others/sys_tracebacklimit.py", line 49, in j
    a / b
ZeroDivisionError: division by zero

Traceback (most recent call last):

  File "tests/exceptions/source/others/sys_tracebacklimit.py", line 33, in f
    g()
    └ <function g at 0xDEADBEEF>

  File "tests/exceptions/source/others/sys_tracebacklimit.py", line 37, in g
    h()
    └ <function h at 0xDEADBEEF>

  File "tests/exceptions/source/others/sys_tracebacklimit.py", line 41, in h
    i()
    └ <function i at 0xDEADBEEF>

  File "tests/exceptions/source/others/sys_tracebacklimit.py", line 45, in i
    j(1, 0)
    └ <function j at 0xDEADBEEF>

  File "tests/exceptions/source/others/sys_tracebacklimit.py", line 49, in j
    a / b
    │   └ 0
    └ 1

ZeroDivisionError: division by zero
